name: Test -- local action -- basic

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Full repository name to generate report for'
        required: true
        default: octodemo-db/demo-vulnerabilities-ghas

      ref:
        description: 'Ref to generate report for'
        required: true
        default: main

      sha:
        description: 'SHA to generate report for'
        required: true
        default: 3231cf1ec9439d1e3984c447b2ee51960ec523e3

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test local action
        uses: ./
        with:
          token: ${{ secrets.SECURITY_ACCESS_TOKEN }}
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          sha: ${{ inputs.sha }}

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: summary.pdf